modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "GNU GPL v3"

[[mods]]
modId = "slskills"
version = "1.0"
displayName = "Sunlit Skills"
description = "A mod that brings out the skill tree for Pufferfishâ€™s Skills from the Society: Sunlit Valley."
authors = "antthLuca"
